# permissions for end users to view tensorboards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tensorboard-viewer-role
rules:
- apiGroups:
  - tensorboard.kubeflow.org
  resources:
  - tensorboards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tensorboard.kubeflow.org
  resources:
  - tensorboards/status
  verbs:
  - get
